package ai.datalithix.kanon.common.security;

public enum Permission {
    TENANT_MANAGE,
    USER_MANAGE,
    ROLE_MANAGE,
    POLICY_MANAGE,
    CONNECTOR_CONFIGURE,
    CONNECTOR_VIEW,
    SOURCE_INGEST,
    SOURCE_VIEW,
    ASSET_VIEW,
    ASSET_DOWNLOAD,
    ANNOTATION_VIEW,
    ANNOTATION_EDIT,
    REVIEW_ASSIGN,
    REVIEW_PERFORM,
    REVIEW_APPROVE,
    WORKFLOW_VIEW,
    WORKFLOW_EXECUTE,
    EVIDENCE_VIEW,
    EVIDENCE_EXPORT,
    MODEL_CONFIGURE,
    MODEL_INVOKE,
    MODEL_VIEW_HEALTH,
    ADMIN_BREAK_GLASS
}
