package ai.datalithix.kanon.common.security;

public enum SecurityEventType {
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    ROLE_ASSIGNMENT_CHANGED,
    PERMISSION_CHANGED,
    CONNECTOR_CONFIGURATION_CHANGED,
    MODEL_PROFILE_CHANGED,
    SOURCE_VIEWED,
    ASSET_DOWNLOADED,
    ANNOTATION_CHANGED,
    REVIEW_APPROVED,
    REVIEW_REJECTED,
    REVIEW_ESCALATED,
    EVIDENCE_EXPORTED,
    BREAK_GLASS_REQUESTED,
    BREAK_GLASS_APPROVED,
    BREAK_GLASS_DENIED,
    BREAK_GLASS_USED,
    UNAUTHORIZED_ACCESS_DENIED,
    INGESTION_PERFORMED,
    INGESTION_FAILED
}
