package ai.datalithix.kanon.common.runtime;

public enum OperationalMetric {
    INGESTION_THROUGHPUT,
    CONNECTOR_LAG,
    WORKFLOW_QUEUE_DEPTH,
    MODEL_INVOCATION_LATENCY,
    MODEL_ERROR_RATE,
    MODEL_FALLBACK_RATE,
    EVIDENCE_WRITE_RATE,
    DATABASE_QUERY_LATENCY,
    OBJECT_STORAGE_LATENCY,
    UI_ENDPOINT_LATENCY,
    AUTHORIZATION_DENIAL_RATE
}
